export const DataAtlas = [
  {
    id: 'gral',
    sede: 'General',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      {img:'desayuno', v:'Desayuno bufete en cortesía'},
      {img:'wifi', v:'Wifi Veloz'},
      {img:'cama', v:'Blackout + Menú de almohadas'},
      {img:'estacionamiento', v:'Estacionamiento gratis'},
      {img:'arte', v:'Arte local en cada habitación'},
      {img:'gym', v:'Gimnasio equipado con LifeFitness'},
      {img:'game', v:'Game Station'},
      {img:'bar', v:'Bar'},
      {img:'alberca', v:'Alberca'},
    ],
  },
  {
    id: 'ags',
    sede: 'Aguascalientes',
    description: `Ubicado en el acceso de la carretera 45 proveniente de Guadalajara, Querétaro, CDMX en plena zona industrial denominada FINSA con complejos con vocación a la industria automotriz, siendo la principal NISSAN de México.<br/><br/>Muy cercano al 3er anillo vial de Aguascalientes por lo que se cuenta con muy buena conexión.<br/><br/>Aeropuerto a aprox. 25 minutos.<br/><br/>Ambientado con murales de “Osvaldo Monos” con temática homenaje a la ciudad, feria de San Marcos, fiesta taurina, palenques y Catrinas (José Guadalupe Posada).`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/aguascalientes-mexico/ramada-encore-aguascalientes/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'vending', value: 'Vending Machine' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
  {
    id: 'gdl',
    sede: 'Guadalajara Sur',
    description: `Se encuentra en La Gourmeteria. Centro comercial dedicado a la recreación y gastronomía. Restaurantes (actualmente 4), bar (Sala de despecho), cine, gimnasio.<br/><br/>Se encuentra en el sur de la ciudad de Guadalajara muy cercano a múltiples terrazas y salones de eventos lo que nos permite otorgar hospedaje a personas tanto foráneas como locales para eventos en dichos salones y terrazas cercanos al hotel.<br/><br/>Cercano a lienzos Charros en Tlajomulco de Zúñiga donde se celebran encuentros charros anualmente.<br/><br/>Ambientado con murales de Jis con temática abstracta.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/guadalajara-mexico/ramada-encore-by-wyndham-guadalajara-sur/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
        { key: 'luggage', value: 'Lugagge Room' },
        { key: 'bebida', value: 'Cupón de bebida en cortesía' },
        { key: 'musica', value: 'Música por las tardes/noches soft rock.' },
        { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
        { key: 'checkin', value: 'Módulo Early Breakfast' },
        { key: 'huevos', value: 'Estación de Omelets.' },
        { key: 'pan', value: 'Pan hecho en el hotel.' },
        { key: 'bar', value: 'Restaurant bar.' },
        { key: 'vending', value: 'Vending Machine' },
        { key: 'room-service', value: 'Room Service' },
        { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
        { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
        { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
        { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
        { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
        { key: 'almohada', value: 'Menú de Almohadas en camas.' },
        { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
        { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
        { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
        { key: 'game', value: 'Game Station' },
        { key: 'billar', value: 'Billar' },
        { key: 'futbolito', value: 'Futbolito' }
      ]
  },
  {
    id: 'gdl-a',
    sede: 'Guadalajara Aeropuerto',
    description: `Ubicado sobre carretera Guadalajara-Chapala a 7 minutos del Aeropuerto Internacional Miguel Hidalgo.<br/><br/>En la zona industrial de El Salto con diversos parques industriales de diversas vocaciones.<br/><br/>El hotel ejecutivo más cercano al aeropuerto.<br/><br/>Cercano a la Arena VFG.<br/><br/>Cercano al Club de Golf Atlas.<br/><br/>Cercano a lienzos Charros en Tlajomulco de Zúñiga.<br/><br/>Ambientado por Trino con temática relacionada con viajes, aeropuertos, aviones, así como íconos turísticos de la ciudad de Guadalajara.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/guadalajara-mexico/ramada-encore-guadalajara-aeropuerto/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'pan', value: 'Pan hecho en el hotel' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'vending', value: 'Mini Store 24/7 en front desk' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness,sponible 24/7.' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
  {
    id: 'mty',
    sede: 'Monterrey',
    description: `Ubicado en el municipio de Apodaca, N.L. Inminentemente industrial con empresas de vocación diversa.<br/><br/>Cercano al Aeropuerto Internacional Mariano Escobedo (20 minutos).<br/><br/>Sobre el acceso principal a la Zona Metropolitana de Monterrey.<br/><br/>Mini Store 24/7 en front desk (excepto SLP).<br/><br/>Ambientado con murales de “Pacasso” con temática sobre el espíritu emprendedor de Nuevo León: personalidades empresariales, industria, arte, gastronomía y arquitectura.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/monterrey-mexico/ramada-encore-onterrey-apodaca-zona-aeropuerto/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'vending', value: 'Mini Store 24/7 en front desk' }
    ],
  },
  {
    id: 'pue',
    sede: 'Puebla',
    description: `Se encuentra ubicado en el acceso de la ciudad de Puebla provenientes de la autopista CDMX-Puebla.<br/><br/>A un costado se encuentra Oulets Premier Puebla, centro comercial outlet con marcas premium.<br/><br/>Ubicado en la denominada zona FINSA. Parques industriales con empresas de la industria automotriz. La planta de Volkswagen siendo la principal.<br/><br/>Hotel ejecutivo de marca más cercano al aeropuerto.<br/><br/>Hotel ejecutivo de marca más cercano a Cholula.<br/><br/>Hotel ejecutivo de marca más cercano a Valquirico.<br/><br/>Ambientado con murales de “Trino” con temática de homenaje al estado de Puebla, su industria, gastronomía, arquitectura, historia y tradiciones.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/puebla-mexico/ramada-encore-puebla-mexico/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'vending', value: 'Vending Machine' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
  {
    id: 'qro',
    sede: 'Querétaro',
    description: `Se encuentra ubicado sobre Paseo de la República en Juriquilla (Carretera 57). Zona de alto desarrollo económico en Querétaro tanto empresarial como comercial. Ubicado a un costado del Centro Comercial Antea (el equivalente a Andares en Guadalajara).<br/><br/>Carretera 57 es la salida hacia San Luis Potosí y hacia el norte del país. Cercanos se encuentran varios parques industriales y tecnológicos.<br/><br/>Se encuentra a 40 minutos de San Miguel de Allende.<br/><br/>Destino vacacional de fin de semana para personas de la CDMX.<br/><br/>Ambientado con murales de Huevocartoon con temática sobre las 7 Bellas Artes.`,
    url: ' https://www.wyndhamhotels.com/es-xl/ramada/queretaro-mexico/ramada-encore-queretaro/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'vending', value: 'Vending Machine' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
  {
    id: 'slp',
    sede: 'San Luis Potosí',
    description: `Se encuentra ubicado accesando a la ciudad sobre carretera 57 (Av. Benito Juárez) provenientes de las ciudades de México, Querétaro, San Luis Potosí en el corazón de la zona industrial.<br/><br/>Entorno a parques industriales y tecnológicos.<br/><br/>En el interior del estacionamiento se encuentra una sucursal Starbucks.<br/><br/>Ambientado con murales de “Alejandro Ochoa” con temática Rally histórico y turístico por el estado de San Luis Potosí.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/san-luis-potosi-mexico/ramada-encore-san-luis-potosi/rooms-rates',
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Cupón de bebida en cortesía' },
      { key: 'musica', value: 'Música ambiental de genero lounge y por las tardes/noches soft rock.' },
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de Omelets.' },
      { key: 'bar', value: 'Restaurant bar.' },
      { key: 'vending', value: 'Vending Machine' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      { key: 'alberca', value: 'Alberca ejecutiva techada, climatizada y con vista panorámica' },
      { key: 'gym', value: 'Gimnasio completo con equipos life Fitness' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes.' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas en camas.' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital en habitación' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito.' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
];