export const DataAtlas = [
  {
    id: 'gral',
    sede: 'General',
    description: `Hoteles diseñados para el viajero moderno que busca practicidad sin sacrificar estilo.<br/><br/>
Ramada Encore by Wyndham combina una arquitectura vanguardista con servicios ejecutivos que garantizan comodidad, eficiencia y una experiencia relajada. Cada sede ofrece desayuno buffet variado, espacios comunes con música lounge, habitaciones con blackout y un ambiente amigable para negocios o descanso.<br/><br/>
Los hoteles cuentan con amenidades consistentes como gimnasio, alberca climatizada (según sede), Room Service, Game Station, billar, futbolito y más.<br/><br/>
Además, cada propiedad integra murales de artistas reconocidos que aportan identidad local a la experiencia del huésped.`,
    street: '1710 Lopez Mateos Sur Ave',
    neighborhood: 'Colonia 1',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.80,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1747953915451!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra en un edificio luminoso junto a la carretera 80, a 11 km del centro de convenciones Expo Guadalajara y a 21 km del Aeropuerto Internacional Miguel Hidalgo y Costilla.',
    amenities: [
      { key: 'luggage', value: 'Lugagge Room' },
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'musica', value: 'Música ambiental de género lounge y soft rock' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'checkin', value: 'Módulo Early Breakfast' },
      { key: 'huevos', value: 'Estación de huevos al gusto' },
      { key: 'bar', value: 'Restaurant bar' },
      { key: 'vending', value: 'Vending Machine o Mini Store 24/7' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada (según sede)' },
      { key: 'gym', value: 'Gimnasio equipado disponible 24/7' },
      { key: 'wifi', value: 'Wifi sin costo para huéspedes' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas (firmes o suaves)' },
      { key: 'caja-seguridad', value: 'Caja de seguridad digital' },
      { key: 'cafeteria', value: 'Cafetera y kit de café en habitación' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      { key: 'game', value: 'Game Station con Xbox' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' }
    ],
  },
  {
    id: 'ags',
    sede: 'Aguascalientes',
    description: `Ubicado en el acceso de la carretera 45 proveniente de Guadalajara, Querétaro, CDMX en plena zona industrial denominada FINSA con complejos con vocación a la industria automotriz, siendo la principal NISSAN de México.<br/><br/>Muy cercano al 3er anillo vial de Aguascalientes por lo que se cuenta con muy buena conexión.<br/><br/>Aeropuerto a aprox. 25 minutos.<br/><br/>Aguascalientes posee la feria más tradicional, reconocida y concurrida de México, celebrándose regularmente entre los meses de abril-mayo de cada año.<br/><br/>Ambientado con murales de “Osvaldo Monos” con temática homenaje a la ciudad, feria de San Marcos, fiesta taurina, palenques y Catrinas (José Guadalupe Posada).`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/aguascalientes-mexico/ramada-encore-aguascalientes/rooms-rates',
    whatsapp: '+5214493638137',
    street: 'Av. Siglo XXI No. 2001',
    neighborhood: 'Parque Industrial FINSA',
    cp: '20354',
    city: 'Aguascalientes',
    state: 'Aguascalientes',
    country: 'México',
    rate: 4.8,
    stars: '★★★★★',
    ratings: 231,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3731.393591507698!2d-102.2939779!3d21.8425889!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8429edb73fb3d299%3A0x53e363de1c2dcc8f!2sRamada%20Encore%20By%20Wyndham%20Aguascalientes!5e0!3m2!1ses!2smx!4v1748801100000!5m2!1ses!2smx',
    mapDescription: 'Hotel ejecutivo ideal para viajeros de negocios en zona industrial FINSA. A corta distancia de la Feria de San Marcos y con acceso ágil al aeropuerto.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'vending', value: 'Vending Machine' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'gdl',
    sede: 'Guadalajara Sur',
    description: `Se encuentra en La Gourmeteria, centro comercial dedicado a la recreación y gastronomía. Cuenta con restaurantes, bar (Sala de despecho), cine y gimnasio.<br/><br/>Ubicado en el sur de la ciudad de Guadalajara, muy cercano a múltiples terrazas y salones de eventos, lo que permite hospedar tanto a personas foráneas como locales que asisten a celebraciones sociales.<br/><br/>Cercano a lienzos Charros en Tlajomulco de Zuñiga donde se celebran encuentros charros anualmente.<br/><br/>Pan hecho en el hotel. Horneado en nuestras cocinas diariamente con variedad de piezas, disponible durante Desayuno buffet en cortesía.<br/><br/>Ambientado con murales de Jis con temática abstracta.<br/><br/>Conectividad de equipo móvil hacia pantalla de TV para transmitir servicios de streaming (Netflix, entre otros).`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/guadalajara-mexico/ramada-encore-by-wyndham-guadalajara-sur/rooms-rates',
    whatsapp: '+5213328043508',
    street: 'Av. López Mateos Sur 1710',
    neighborhood: 'Tlajomulco, Plaza La Gourmetería',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.8,
    stars: '★★★★★',
    ratings: 197,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.4943520948136!2d-103.4488361015852!3d20.586878901850287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f54b8dc35bb6f%3A0xc5acad50c63f0fee!2sRamada%20Encore%20Guadalajara%20Sur!5e0!3m2!1ses!2smx!4v1748802000000!5m2!1ses!2smx',
    mapDescription: 'Este hotel informal se encuentra dentro de La Gourmetería, una plaza gastronómica y de entretenimiento al sur de Guadalajara, ideal para quienes asisten a eventos o buscan una experiencia más local.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'pan', value: 'Pan recién horneado' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'gdl-a',
    sede: 'Guadalajara Aeropuerto',
    description: `Ubicado sobre carretera Guadalajara-Chapala a 7 minutos del Aeropuerto Internacional Miguel Hidalgo.<br/><br/>En la zona industrial de El Salto con diversos parques industriales de diversas vocaciones.<br/><br/>El hotel ejecutivo más cercano al aeropuerto.<br/><br/>Cercano a la Arena VFG donde se celebran conciertos masivos de artistas tanto nacionales como internacionales.<br/><br/>Cercano al Club de Golf Atlas, en donde se celebran torneos anuales de Golf.<br/><br/>Cercano a lienzos Charros en Tlajomulco de Zuñiga donde se celebran encuentros charros anualmente.<br/><br/>Pan hecho en el hotel. Horneado en nuestras cocinas diariamente con variedad de piezas, disponible durante Desayuno buffet en cortesía.<br/><br/>Room Service Nocturno con horario extendido con platillos seleccionados hasta las 6:00am.<br/><br/>Mini Store 24/7 en front desk.<br/><br/>Ambientado por Trino con temática relacionada con viajes, aeropuertos, aviones así como íconos turísticos de la ciudad de Guadalajara.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/guadalajara-mexico/ramada-encore-guadalajara-aeropuerto/rooms-rates',
    whatsapp: '+5213332421441',
    street: 'Carr. Guadalajara - Chapala 7610',
    neighborhood: 'El Salto',
    cp: '45693',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.7,
    stars: '★★★★★',
    ratings: 214,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9680.290568827484!2d-103.3056407!3d20.5508166!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842f4d6fd2278261%3A0xb31e84592c7679b8!2sRamada%20Encore%20by%20Wyndham%20Guadalajara%20Aeropuerto!5e1!3m2!1ses!2sus!4v1748971571004!5m2!1ses!2sus',
    mapDescription: 'Hotel de negocios ubicado estratégicamente a minutos del aeropuerto, ideal para viajeros frecuentes y asistentes a eventos en Arena VFG o Club de Golf Atlas.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'pan', value: 'Pan recién horneado' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service Nocturno hasta las 6:00am' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones con instalaciones “Black Out”' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'vending', value: 'Mini Store 24/7 en front desk' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'mty',
    sede: 'Monterrey Apodaca',
    description: `Ubicado en el municipio de Apodaca, Nuevo León, una zona eminentemente industrial con empresas de vocación diversa.<br/><br/>Cercano al Aeropuerto Internacional Mariano Escobedo (20 minutos) y sobre el acceso principal a la Zona Metropolitana de Monterrey.<br/><br/>Mini Store 24/7 en front desk (excepto SLP). Venta de refrescos, botanas, dulces así como artículos de higiene personal y medicamento básico.<br/><br/>Room Service nocturno con horario extendido con platillos seleccionados hasta las 3:00am.<br/><br/>Ambientado con murales de “Pacasso” con temática sobre el espíritu emprendedor de Nuevo León. Personalidades empresariales, industria, arte, gastronomía y arquitectura.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/monterrey-mexico/ramada-encore-onterrey-apodaca-zona-aeropuerto/rooms-rates',
    whatsapp: '+5218121711558',
    street: 'Blvd. Aeropuerto 400',
    neighborhood: 'Parque Industrial Nexxus Apodaca',
    cp: '66600',
    city: 'Apodaca',
    state: 'Nuevo León',
    country: 'México',
    rate: 4.6,
    stars: '★★★★★',
    ratings: 185,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3584.971344606474!2d-100.1910957!3d25.7739336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8662ebcf670102a9%3A0x3991612cc341021f!2sRamada%20Encore%20by%20Wyndham%20Monterrey%20Apodaca%20Zona%20Aeropuerto!5e0!3m2!1ses!2smx!4v1748802300000!5m2!1ses!2smx',
    mapDescription: 'Hotel ejecutivo en Apodaca, ideal para viajeros corporativos. A minutos del aeropuerto y con acceso rápido a parques industriales.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service Nocturno hasta las 3:00am' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones con “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'vending', value: 'Mini Store 24/7 en front desk' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'pue',
    sede: 'Puebla',
    description: `Ubicado en el acceso de la ciudad de Puebla provenientes de la autopista CDMX-Puebla, junto a Oulets Premier Puebla, un centro comercial con marcas premium.<br/><br/>Situado en la zona FINSA, rodeado de parques industriales y empresas automotrices. La planta de Volkswagen es la más cercana e importante en la región.<br/><br/>Hotel ejecutivo de marca más cercano al aeropuerto (20 minutos), a Cholula (20–25 minutos) y a Valquirico, un centro turístico tipo pueblo italiano con oferta gastronómica y de entretenimiento.<br/><br/>Puebla es una ciudad con vocación turística, famosa por su centro histórico barroco y su gastronomía reconocida a nivel nacional e internacional.<br/><br/>Ambientado con murales de “Trino” en homenaje al estado de Puebla, su historia, industria, arquitectura y cultura.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/puebla-mexico/ramada-encore-puebla-mexico/rooms-rates',
    whatsapp: '+5212202282861',
    street: 'Autopista México - Puebla Km. 117',
    neighborhood: 'Zona FINSA',
    cp: '72640',
    city: 'Puebla',
    state: 'Puebla',
    country: 'México',
    rate: 4.7,
    stars: '★★★★★',
    ratings: 203,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.1529679911955!2d-98.2711627!3d19.1348196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85cfc5160849afb7%3A0xbc123d6c2c2b2744!2sRamada%20Encore%20by%20Wyndham%20Puebla!5e0!3m2!1ses!2smx!4v1748802500000!5m2!1ses!2smx',
    mapDescription: 'Hotel ejecutivo y turístico en la entrada a Puebla. Ideal para negocios, escapadas a Cholula, Valquirico o visitas a la planta Volkswagen.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'vending', value: 'Vending Machine' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'qro',
    sede: 'Querétaro',
    description: `Ubicado sobre Paseo de la República en Juriquilla (Carretera 57), zona de alto desarrollo económico y empresarial.<br/><br/>A un costado del centro comercial Antea, el más exclusivo de la ciudad, con fácil acceso hacia San Luis Potosí y el norte del país.<br/><br/>A 40 minutos de San Miguel de Allende y destino vacacional de fin de semana para visitantes provenientes de la CDMX.<br/><br/>Ambientado con murales de Huevocartoon con temática inspirada en las 7 Bellas Artes.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/queretaro-mexico/ramada-encore-queretaro/rooms-rates',
    whatsapp: '+5214428128461',
    street: 'Paseo de la República 11515',
    neighborhood: 'Juriquilla',
    cp: '76127',
    city: 'Querétaro',
    state: 'Querétaro',
    country: 'México',
    rate: 4.6,
    stars: '★★★★☆',
    ratings: 189,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3734.978748150425!2d-100.4400512!3d20.6694802!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8662be3881681037%3A0x4ce3d44348c95489!2sRamada%20Encore%20Quer%C3%A9taro!5e0!3m2!1ses!2smx!4v1748802800000!5m2!1ses!2smx',
    mapDescription: 'Hotel moderno en zona empresarial de Juriquilla, junto al centro comercial Antea y con conexión directa a la carretera 57. Ideal para negocios y turismo.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto.' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'vending', value: 'Vending Machine' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  },
  {
    id: 'slp',
    sede: 'San Luis Potosí',
    description: `Ubicado sobre la carretera 57 (Av. Benito Juárez), en el corazón de la zona industrial, con fácil acceso desde México, Querétaro y otras ciudades del centro-norte del país.<br/><br/>Rodeado de parques industriales y tecnológicos; a 25-30 minutos de la planta GM y 30-35 minutos de la planta BMW.<br/><br/>En el interior del estacionamiento se encuentra una sucursal Starbucks.<br/><br/>Ambientado con murales de “Alejandro Ochoa” con temática de rally histórico y turístico por el estado de San Luis Potosí.`,
    url: 'https://www.wyndhamhotels.com/es-xl/ramada/san-luis-potosi-mexico/ramada-encore-san-luis-potosi/rooms-rates',
    whatsapp: '+5214443690820',
    street: 'Av. Benito Juárez 3963',
    neighborhood: 'Zona Industrial',
    cp: '78395',
    city: 'San Luis Potosí',
    state: 'San Luis Potosí',
    country: 'México',
    rate: 4.5,
    stars: '★★★★☆',
    ratings: 174,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3735.9842039826634!2d-100.8984929!3d22.112036!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842aa3b9dc187c91%3A0xd1ff83504c2b2f36!2sRamada%20Encore%20San%20Luis%20Potosi!5e0!3m2!1ses!2smx!4v1748808000000!5m2!1ses!2smx',
    mapDescription: 'Hotel ejecutivo en la zona industrial de San Luis Potosí, ideal para estancias de negocios. Cuenta con Starbucks dentro del estacionamiento y fácil acceso a plantas automotrices cercanas.',
    amenities: [
      { key: 'bebida', value: 'Bebida cortesía en bienvenida' },
      { key: 'buffet', value: 'Desayuno buffet en cortesía' },
      { key: 'huevos', value: 'Estación de huevos al gusto' },
      { key: 'bar', value: 'Restaurante – Bar' },
      { key: 'game', value: 'Game Station' },
      { key: 'billar', value: 'Billar' },
      { key: 'futbolito', value: 'Futbolito' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones “Black Out” total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'luggage', value: 'Lugagge Room' },
      // { key: 'musica', value: 'Música ambiental soft rock.' },
      // { key: 'checkin', value: 'Módulo Early Breakfast' },
      // { key: 'vending', value: 'Vending Machine' },
      // { key: 'llamadas', value: 'Llamadas telefónicas nacionales sin costo.' },
      // { key: 'lavanderia', value: 'Servicio de lavandería y tintorería.' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
    ]
  }
];